[package]
name = "ainojimakugumi"
description = "aI NO jimaKu gumI, a sub-title maker using AI."
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "7.1.0"
hound = "3.5.1"
whisper-rs = "0.13.2"

[dev-dependencies]
hound = "3.5.1"
